// <auto-generated />
using Datos.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(ShingekiContext))]
    [Migration("20260505140000_BranchOperationalSettings")]
    partial class BranchOperationalSettings
    {
    }
}
